[build]
builder = "DOCKERFILE"
watchPatterns = ["**/*"]

[deploy]
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100
